main/urls.py
from django.conf.urls import url
#from django.contrib import admin
from .import views

app_name = 'main'

urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^list', views.list, name='list'),
  url(r'^buy', views.buy, name='buy'),
  url(r'^login',views.login_regis_view,name='login_regis'),
  url(r'^doregis',views.do_regis,name='regis'),
  url(r'^dologin',views.do_login,name='login'),
  url(r'^history',views.history,name='history'),
  url(r'^logout',views.do_logout,name='logout'),
  url(r'^topup',views.topup,name='topup'),
  url(r'^mainforum/$',views.mainforum,name='mainforum'),
  url(r'^postQuestion/$',views.postQuestion,name='postQuestion'),
  url(r'^viewQuestion/$',views.viewQuestion,name='viewQuestion'),
  url(r'^replyQuestion/$',views.replyQuestion,name='replyQuestion'),
  url(r'^edit/$',views.edit,name='edit'),
  url(r'^deleteQuestion/$',views.deleteQuestion,name='deleteQuestion'),
]

pigpugpong/urls.py
from django.conf.urls import url,include
from django.contrib import admin

app_name = 'main'

urlpatterns = [
    url(r'^',include('main.urls')),
    url(r'^admin/', admin.site.urls),
]

main/models.py
import datetime
from django.db import models

class Accounts (models.Model) :
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=15)
    email = models.CharField(max_length=30)
    password = models.CharField(max_length=20)

    def __str__(self):
        return u'id : %s ( %s )' % (self.user_id , self.username)

class Order (models.Model) :
    order_id = models.AutoField(primary_key=True)
    user_id = models.IntegerField()
    top_up_type_id = models.IntegerField()
    package_id = models.IntegerField()
    date_order = models.DateTimeField()
    date_paid = models.DateTimeField()
    date_count = models.IntegerField(3);
    status = models.CharField(max_length=10)
    top_up_code = models.CharField(max_length=100)
    payment_code = models.CharField(max_length=30)

    def __str__(self):
        return u'id : %s' % self.order_id

class User_Wallet (models.Model) :
    user_id = models.IntegerField();
    money = models.IntegerField();
    point = models.IntegerField(default=1);

class Package (models.Model) :
    package_id = models.AutoField(primary_key=True)
    top_up_type_id = models.ForeignKey('Top_Up_Type')
    value = models.IntegerField();
    price = models.IntegerField();
    point = models.IntegerField(default=1);

    def __str__(self):
        return u'id : %s' % self.package_id

class Top_Up_Type (models.Model) :
    top_up_type_id = models.AutoField(primary_key=True)
    TYPE_NAME_CHOICES = (
        ('STEAM','steam'),
        ('LINE','line'),
        ('PLAY_STATION','play_station')
    )
    type_name = models.CharField(max_length=20,choices=TYPE_NAME_CHOICES)
    image_path = models.CharField(max_length=100)

    def __str__(self):
        return u'id : %s ( %s )' % (self.top_up_type_id ,self.type_name)

class Truemoney (models.Model) :
    value = models.IntegerField();
    card_id = models.CharField(max_length=14)

class Question(models.Model) :
    question_id = models.AutoField(primary_key=True)
    question_subject = models.CharField(max_length=200)
    question_detail = models.CharField(max_length=1000)
    user_id = models.IntegerField()
    question_date = models.DateTimeField()

class Reply(models.Model) :
    reply_id = models.AutoField(primary_key=True)
    reply_detail = models.CharField(max_length=500)
    question_id = models.FloatField()
    user_id = models.IntegerField()
    reply_date = models.DateTimeField()

main/views.py
from django.shortcuts import render
from main.models import Top_Up_Type,Package,Order,User_Wallet,Truemoney,Question,Reply
from .models import Accounts
from datetime import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
import random
# Create your views here.
def index(request) :
    if 'username' not in request.session:
        return render(request,'index.html',{'username':'','user_id':''})
    else:
        username = request.session[ 'username' ]
        user_id = request.session[ 'username' ]
        a = Top_Up_Type.objects.all()
        return render(request,'index.html',{'username':request.session[ 'username' ],'user_id':request.session[ 'id' ]})

def getPackageList(key) :
    if key == 'steam' :
      return  Package.objects.filter( top_up_type_id=int(1) )
    elif key == 'line':
      return  Package.objects.filter( top_up_type_id=int(2) )
    else:
      return  Package.objects.filter( top_up_type_id=int(3) )

def getTopUpTypeID(key) :
    if key == 'steam' :
      return  1
    elif key == 'line':
      return  2
    else:
      return  3

def list(request) :
    key = request.POST['key']
    package_list = getPackageList(key)
    if 'username' not in request.session:
        return render(request,'list.html',{'key':key,'x':package_list,'username':'','user_id':'','user':''})
    else:
        user = User_Wallet.objects.get(user_id=request.session['id'])
        return render(request,'list.html',{'key':key,'x':package_list,'username':request.session[ 'username' ],'user_id':request.session[ 'id' ],'error':'n','user':user})

def buy(request) :
    key = request.POST['key']
    package_list = getPackageList(key)
    top_up_type_id = getTopUpTypeID(key)
    if 'username' not in request.session:
        return render(request,'list.html',{'key':key,'x':package_list,'username':'','user_id':'','user':''})
    else:
        method = request.POST['method']
        package_id = request.POST['package_id']
        user_id = request.session[ 'id' ]
        price = request.POST['price']
        point = request.POST['point']

        payment_code = ''
        top_up_code = ''
        status="notpaid"
        current_point = User_Wallet.objects.get(user_id=request.session['id'])
        user = User_Wallet.objects.get(user_id=request.session['id'])
        if method == 'wallet':
            status="ready"
            top_up_code = getSteamCode()
            current_value = User_Wallet.objects.get(user_id=request.session['id']);
            package_value = Package.objects.get(package_id=package_id)
            package_point = Package.objects.get(package_id=package_id)
            if int(current_value.money) < int(package_value.price) :
                return render(request,'list.html',{'key':key,'x':package_list,'username':request.session[ 'username' ],'user_id':request.session[ 'id' ],'error':'y','user':user})
            else :
              new_value = int(current_value.money)-int(price)
              new_point = int(current_point.point)+int(package_point.point)
              User_Wallet.objects.filter( user_id=request.session['id']).update(money=new_value,point=new_point)
        else:
            status="notpaid"
            payment_code = get7code()

        db = Order(user_id=user_id, top_up_type_id=top_up_type_id, package_id=package_id, date_order=datetime.now() ,date_paid=datetime.now(),date_count='1',status=status,top_up_code=top_up_code,payment_code=payment_code)
        db.save()
        return history(request)

def login_regis_view( request ) :
    if 'username' not in request.session:
        return render(request, 'login_register_view.html',{'username':'','user_id':''})
    else:
        return render(request, 'login_register_view.html',{'username':request.session[ 'username' ],'user_id':request.session[ 'id' ]})

def do_login( request ) :
    if request.method == "POST" :
        _login_key = request.POST.get( "login_key" )
        _login_pass = request.POST.get( "login_password" )

        row = Accounts.objects.filter( username=_login_key, password=_login_pass )
        user = None
        if not row:
            row = Accounts.objects.filter( email=_login_key, password=_login_pass )

        if not row :
            request.session[ 'notice' ] = "user not found"
            return render( request, 'login_register_view.html')
        user = row[0]

        request.session[ 'username' ] = user.username
        request.session[ 'id' ] = user.user_id
        request.session[ 'email' ] = user.email

    print('test session : ')
    print(request.session[ 'id' ])
    print(request.session[ 'email' ])
    return render( request, 'index.html',{'username':request.session[ 'username' ],'user_id':request.session[ 'id' ]} )

def do_regis( request ):

    _username = request.POST['regis_username']
    _email = request.POST['regis_email']
    _pass = request.POST['regis_password']
    _con_pass = request.POST['regis_confirmpassword']

    if _pass == _con_pass :
        new_account = Accounts( username=_username, email=_email, password=_pass )
        new_account.save()
        _user_id = Accounts.objects.get( username = _username )

        new_wallet = User_Wallet( user_id=_user_id.user_id, money='0')
        new_wallet.save();

        request.session[ 'notice' ] = "Successful create accounts"
        request.session[ 'username' ] = new_account.username
        return render( request, "login_register_view.html" )
    else :
        request.session[ 'notice' ] = "Password incorrect"
        return render( request, "login_register_view.html" )

        return render( request, 'index.html' )
    # return render( request, 'index.html' )
    # return HttpResponseRedirect('/login/')

def do_logout ( request ):
    del request.session['username']
    del request.session['id']
    return render( request, "login_register_view.html")

def history(request) :
    if 'username' not in request.session:
        return render(request,'index.html',{'username':'','user_id':''})
    else:
        user_id = request.session[ 'id' ]
        account = Accounts.objects.get(user_id=user_id)
        order = Order.objects.filter(user_id=account.user_id)
        # results = Order.objects.extra(tables=["Top_Up_Type"],
        #                   where=["""Top_Up_Type.top_up_type_id = Order.top_up_type_id"""])
        user_wallet = User_Wallet.objects.get(user_id=user_id);

        return render(request,'history.html',{'order':order ,'username':request.session[ 'username' ],'user_id':request.session[ 'id' ],'email':request.session[ 'email'],'wallet':user_wallet})

def get7code() :
    tmp = ""
    i = 0
    while i < 30 :
        tmp = tmp + str( random.randint( 0, 9 ) )
        i += 1
    return tmp

def getSteamCode() :
    tmp = ""
    i = 1
    while i <= 15 :
        if random.randint( 0, 1 ) == 1 :
            tmp = tmp + str( chr( random.randint( 97, 122 ) ) )
        else :
            tmp = tmp + str( random.randint( 0, 9 ) )
        if i % 5 == 0 and i != 15 :
            tmp = tmp + str( "-" )
        i += 1
    return tmp

def getPSCode() :
    tmp = ""
    i = 1
    while i <= 12 :
        if random.randint( 0, 1 ) == 1 :
            tmp = tmp + str( chr( random.randint( 97, 122 ) ) )
        else :
            tmp = tmp + str( random.randint( 0, 9 ) )
        if i % 4 == 0 and i != 12 :
            tmp = tmp + str( "-" )
        i += 1
    return tmp

def edit(request):
    new_username = request.POST['username']
    new_email = request.POST['email']
    Accounts.objects.filter( user_id=request.session['id']).update(username=new_username,email=new_email)
    user_id = request.session[ 'id' ]
    account = Accounts.objects.get(user_id=user_id)

    request.session[ 'username' ] = account.username
    request.session[ 'id' ] = account.user_id
    request.session[ 'email' ] = account.email

    return history(request)

def topup(request) :
    code_id = request.POST['code_id']
    value = Truemoney.objects.filter(card_id=code_id)
    current_value = User_Wallet.objects.get(user_id=request.session['id']);
    new_value = int(value[0].value)+int(current_value.money)

    User_Wallet.objects.filter( user_id=request.session['id']).update(money=new_value)

    return history(request)

def mainforum(request):
    if 'username' not in request.session:
        return render(request,'index.html',{'username':'','user_id':''})
    else:
        question_list = Question.objects.all()
        account_list = Accounts.objects.all()
        return render(request,'mainforum.html',{'username':request.session['username'],'question_list':question_list,'account_list':account_list})

def postQuestion(request):
    if 'username' not in request.session:
        return render(request,'mainforum.html',{'username':'','user_id':''})
    else:
        question_subject = request.POST['question_subject']
        question_detail = request.POST['question_detail']
        user_id = request.session[ 'id' ]
        question = Question.objects.create(question_subject=question_subject,question_detail=question_detail,user_id=user_id,question_date=datetime.now())
        question.save()
        return HttpResponseRedirect(reverse('main:mainforum'))

def viewQuestion(request):
    if 'username' not in request.session:
        return render(request,'index.html',{'username':'','user_id':''})
    else:
        account_list = Accounts.objects.all()
        try :
            print ('------------------',request.POST['select_question'])
            question = Question.objects.get(question_id=request.POST['select_question'])
            print('1111')
            reply = Reply.objects.filter(question_id=question.question_id)
            print('2222')
        except KeyError :
            question = Question.objects.get(question_id=request.session['replyQuestion'])
            reply = Reply.objects.filter(question_id=question.question_id)
            del request.session['replyQuestion']

main/templates/data-toggle.html
<form class="-inline" id="add-top-up">
  <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal">
    Top-up
  </button>
</form>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Please input your top-up code</h4>
      </div>
      <div class="modal-body">
        <div class="container -method-container topup-modal">
          <img class="center" src = "../static/images/truemoney.jpg" alt="" height="200" >
          <form class= "-inline" action = "{% url 'main:topup' %}" method = "post">{% csrf_token %}
            <input type="text" class="form-control width-200" name="code_id">
            <button class="btn btn-success" class = "wallet" type = "submit"> Submit </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

main/templates/logout.html
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right" style="color:white;">
      <div class="padding-top">
        <form class="-inline" action="{% url 'main:history' %}" method="post">{% csrf_token %}
          <button type="submit" class="btn btn glyphicon glyphicon-user bold-login black">{{username}}</button>
        </form>
        <form class="-inline" action="{% url 'main:logout' %}" method="post">{% csrf_token %}
          <button type="submit" class="btn btn-danger">Log out</button>
        </form>
        </div>
    </ul>
</div>

main/templates/mainforum.html
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->
<!-- HEAD SECTION -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>PIG PUG PONG TOP-UP</title>
    <style>
    textarea {overflow-y: scroll; overflow-x: scroll;}
    td {text-align: left;vertical-align: text-top;}
    </style>
    <!--GOOGLE FONT -->
    {% load staticfiles %}
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <!--BOOTSTRAP MAIN STYLES -->
    <link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet" />
    <!--FONTAWESOME MAIN STYLE -->
    <link href="{% static 'assets/css/font-awesome.min.css' %}" rel="stylesheet" />
    <!-- <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"> -->
    <!--SLIDER CSS CLASES -->
    <link href="{% static 'assets/Slides-SlidesJS-3/examples/playing/css/slider.css' %}" rel="stylesheet" />
    <!--CUSTOM STYLE -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/session_bar.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/veiwQ.css' %}" rel="stylesheet" />
    <!-- <link href="{% static 'assets/css/list.css' %}" rel="stylesheet" /> -->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<!--END HEAD SECTION -->
<body>
    <!-- NAV SECTION -->
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'main:index' %}">PIGPUGPONG</a>
            </div>
                {% include "logout.html" %}
        </div>
    </div>
    <!--END NAV SECTION -->
    <!-- HOME SECTION -->
    <div class="container">
    <ul class="nav nav-tabs">
      <li role="presentation" class="active" id="home_tab"><a href="#mainforum">Home</a></li>
      <li role="presentation" id="new_question_tab"><a href="#New_question">Post</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane fade active in"  id="main_forum">
        <div class="row">
          <table class="table">
            <th style="width: 50%">Subject</th>
            <th style="width: 35%">Writer</th>
            <th style="width: 20%"></th>
            {% for question in question_list %}
            <tr>
              <td>{{ question.question_subject }}</td>
              {% for account in account_list %}
                {% if question.user_id == account.user_id %}
                  <td>{{ account.username }}</td>
                {% endif %}
              {% endfor %}
              <td>
                <form action="{% url 'main:viewQuestion' %}" method="POST" id="question">
                  {% csrf_token %}
                  <button class="btn btn-primary btn-lg btn-style" name="select_question" value="{{ question.question_id }}">View</button>
                </form>
              </td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
      <div class="tab-pane fade" id="new_question">
        <form action="{% url 'main:postQuestion' %}" method="POST">
          {% csrf_token %}
          <table>
            <tr>
              <td>Question Subject:</td>
              <td><input class="form-control" type="text" placeholder="question subject" name="question_subject"></td>
            </tr>
            <tr>
              <td>Question Details :</td>
              <td>
                <textarea class="form-control" placeholder="question detail" rows="20" cols="100" name="question_detail"></textarea>
              </td>
            </tr>
          </table>
          <button class="btn btn-primary btn-lg" name="postQuestion">Submit</button>
        </form>
      </div>
    </div>

    </div>


    <!--END HOME SECTION -->

    <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
    <!-- CORE JQUERY LIBRARY -->
    {% load static %}
    <script src="{% static 'assets/js/jquery.js' %}"></script>
    <!-- CORE BOOTSTRAP LIBRARY -->
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/profile.js' %}"></script>
    <!-- SLIDER SCRIPTS LIBRARY -->
    <script src="{% static 'assets/Slides-SlidesJS-3/examples/playing/js/jquery.slides.min.js' %}"></script>
    <!-- CUSTOM SCRIPT-->
    <script>
        $(document).ready(function () {
            $('#slides').slidesjs({
                width: 940,
                height: 528,
                play: {
                    active: true,
                    auto: true,
                    interval: 4000,
                    swap: true
                }
            });
            $('#new_question_tab').click(function(){
              $("#home_tab").removeClass("active");
              $("#new_question_tab").addClass("active");
              $("#main_forum").removeClass('active in');
              $("#new_question").addClass('active in');
            });
            $('#home_tab').click(function(){
              $("#new_question_tab").removeClass("active");
              $("#home_tab").addClass("active");
              $("#new_question").removeClass('active in');
              $("#main_forum").addClass('active in');
            });
        });
    </script>
</body>
</html>

main/templates/viewQuestion.html
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->
<!-- HEAD SECTION -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>PIG PUG PONG TOP-UP</title>
    <style>
    textarea {overflow-y: scroll; overflow-x: scroll;}
    td {text-align: left;vertical-align: text-top;}
    .list-group {
        padding: 10px;
        border-radius: 5px;
        margin: 10px;
    }
    .hd{
      background-color: #D5D3D3;
    }
    .sc{
      line-height: 3;
      overflow-y: scroll;
    }
    .row{
      padding: 10px;
    }
    .panel-body{
      line-height: 5;
      overflow-y: scroll;
    }
    </style>
    <!--GOOGLE FONT -->
    {% load staticfiles %}
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <!--BOOTSTRAP MAIN STYLES -->
    <link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet" />
    <!--FONTAWESOME MAIN STYLE -->
    <link href="{% static 'assets/css/font-awesome.min.css' %}" rel="stylesheet" />
    <!-- <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"> -->
    <!--SLIDER CSS CLASES -->
    <link href="{% static 'assets/Slides-SlidesJS-3/examples/playing/css/slider.css' %}" rel="stylesheet" />
    <!--CUSTOM STYLE -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/session_bar.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/veiwQ.css' %}" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<!--END HEAD SECTION -->
<body>
    <!-- NAV SECTION -->
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'main:index' %}">PIGPUGPONG</a>
            </div>
                {% include "logout.html" %}
        </div>
    </div>
    <!--END NAV SECTION -->
    <!-- HOME SECTION -->

    <!-- <div class="btn-group" role="group" aria-label="Basic example">
      <button type="button" class="btn btn-secondary">Left</button>
      <button type="button" class="btn btn-secondary">Middle</button>
      <button type="button" class="btn btn-secondary">Right</button>
    </div> -->


    <div class="container">
            <div class="panel panel-default">
          <div class="panel-heading">
            <div class="btn-group pull-right" role="group">
              <div class="col-md-6">
                <form action="{% url 'main:mainforum' %}" method="post">
                  {% csrf_token %}
                  <div class="row"><button type="submit" class="btn btn-primary" name=mainforum>Back</button></div>
                </form>
              </div>
              <div class="col-md-6">
                <form action="{% url 'main:deleteQuestion' %}" method="POST">
                  {% csrf_token %}
                  <div class="row"><button class="btn btn-primary" name="deleteQuestion" value={{select_question.question_id}}>Delete</a></div>
                </form>
              </div>
            </div>
            <h4>Subject :{{select_question.question_subject}}</h4>
          </div>
          <div class="panel-body">
            <div class="row"><p>Detail :</p></div>
            <div class="row"><p>{{select_question.question_detail}}<p></div>
            <div class="row"><p class="text-right">{{select_question.question_date}}</p></div>
          </div>
        </div>


      <div class="row">
        <form action="{% url 'main:replyQuestion' %}" method="POST">
          {% csrf_token %}
          <div class="col-md-10"><input class="form-control" type="text" placeholder="reply" name="reply_question"></div>
          <div class="col-md-2">
            <button class="btn btn-primary btn-lg btn-style -padding" name="replyQuestion" value={{select_question.question_id}}>Reply</button>
          </div>
        </form>
      </div>




      <div class="list-group">
      {% for reply in reply_list %}
        <a href="#" class="list-group-item">
                <div class="row hd">
                {% for account in account_list %}
                  {% if reply.user_id == account.user_id %}
                    <h4 class="list-group-item-heading">{{ account.username }}</h4>
                  {% endif %}
                {% endfor %}
                </div>
                <div class="row sc">
                <p class="list-group-item-text">{{reply.reply_detail}}</p><br>
                <p class="list-group-item-text">{{reply.reply_date}}</p><br>
                </div>
        </a>
      {% endfor %}
    </div>
    </div>


    <!--END HOME SECTION -->

    <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
    <!-- CORE JQUERY LIBRARY -->
    {% load static %}
    <script src="{% static 'assets/js/jquery.js' %}"></script>
    <!-- CORE BOOTSTRAP LIBRARY -->
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/profile.js' %}"></script>
    <!-- SLIDER SCRIPTS LIBRARY -->
    <script src="{% static 'assets/Slides-SlidesJS-3/examples/playing/js/jquery.slides.min.js' %}"></script>
    <!-- CUSTOM SCRIPT-->
    <script>
        $(document).ready(function () {
            $('#slides').slidesjs({
                width: 940,
                height: 528,
                play: {
                    active: true,
                    auto: true,
                    interval: 4000,
                    swap: true
                }
            });
        });
    </script>
</body>
</html>